config/routes.rb
Rails.application.routes.draw do
  root 'boards#index'
  
  devise_for :users

  resources :boards do
    resources :lists
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :lists
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

has_many :boards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!


  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :username])
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController 
    before_action :set_board_id, only: [:show, :edit, :update, :destroy]
  
    def index
      @boards = current_user.boards
    end
  
    def show
      @lists = @board.lists
    end
  
    def new
      @board = current_user.boards.new
    end
  
    def create
      @board = current_user.boards.new(board_params)
  
      if @board.save
        
        redirect_to boards_path
      else
        render :new
      end
    end
    
    def edit
    end
  
    def update
      if @board.update(board_params)
        redirect_to boards_path
      else
        render :edit
      end
    end
  
    def destroy
      @board.destroy
      redirect_to boards_path
    end
  
    private
      def board_params
        params.require(:board).permit(:name)
      end
      def set_board_id
        @board = current_user.boards.find(params[:id])
      end
  end
  

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  before_action :set_board
  before_action :set_list, only: [:show, :edit, :destroy]
  
  def index
    @lists = @board.lists
  end

  def show
  end

  def new
    @list = @board.lists.new
  end

  def create
    @list = @board.lists.new(list_params)

    if @list.save
      redirect_to @board
    else
      render :new
    end

  end

  def edit
    if @list.update(list_params)
      redirect_to @list
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to @board
  end



  private

  def set_board
    @board = Board.find(params[:board_id])
  end

  def set_list
    @list = @board.lists.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/boards/edit.html.erb
<%= render 'layouts/board-form' %>

app/views/boards/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>

<h2>Welcome <%= current_user.name %></h2>

<h3>My Boards</h3>

<%= link_to "Add Board", new_board_path %>

<% @boards.each do |b| %>
  <ul>
    <li><%= link_to b.name, board_path(b) %>  |  <%= link_to 'Edit Board Title', edit_board_path(b) %>  |  <%= link_to "Delete Board", b, method: :delete  %></li>
  </ul>
<% end %>

app/views/boards/new.html.erb
<h1>Boards</h1>
<%= render 'layouts/board-form' %>

app/views/boards/show.html.erb
<h1><%= @board.name %></h1>
<br>
<%= link_to "Add List", new_board_list_path(@board) %>
<br>
<ul>
<% @lists.each do |list| %>
  <li><%=link_to list.name, board_list_path(@board, list.id) %>
  <% end %>
</ul>

app/views/layouts/_board-form.html.erb
<div class="form-wrapper">
<h1><%= @board.id ? "Edit Board" : "Create New Board" %> </h1>

  <%= form_for @board do |b| %> 
    <%= b.label :name %>
    <%= b.text_field :name %>
    <%= b.submit %>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav>
<div class="ui menu">
  <div class="header item">
  <a href="#">Trello Clone</a>
</div>
  <ul>
    <li class="item"><%= link_to 'Home', root_path %></li>
    <li class="item"><%= link_to 'My Boards', boards_path %></li>
    <li class="item"><%= link_to 'Create Board', new_board_path %></li>
  </ul>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloClone2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>Lists#edit</h1>
<p>Find me in app/views/lists/edit.html.erb</p>

app/views/lists/index.html.erb
<h1>Lists</h1>

<% @lists.each do |list| %>
  <li> <%= link_to list.title, boards_list_path(@board, list.id) %></li>

 
<% end %>

app/views/lists/new.html.erb
<h1><%= @board.name %></h1>
<br>

<p>Create a new list:</p>
<br>
<%= form_with(model: [@board, @list], local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true %>

  <%= f.submit %>

  <% end %>

app/views/lists/show.html.erb
<h1>My Lists</h1>

<form action="/action_page.php" id="usrform">
  Title: <input type="text" name="usrname">

</form>


<p>Description:</p>
  <textarea rows="4" cols="50" name="comment" form="usrform">
  Enter text here...</textarea>
  <br>
  <button type="save list" value="Save List">Save List</button>
<br>
<br>

<%= link_to "Back To My Boards", boards_path%>